import { DesignProps } from "../types";

/**
 * Vira UI Presets - Готовые наборы стилей для компонентов
 * Используйте их для быстрой разработки без написания CSS
 * 
 * Все presets используют токены темы для максимальной гибкости и адаптивности
 */
export const presets = {
  // ===== БАЗОВЫЕ =====
  default: {
    padding: 2,
    radius: "radius.md",
    transition: "all 0.2s",
  } as DesignProps,

  interactive: {
    transition: "transform 0.15s ease",
    hover: {
      transform: "translateY(-2px)",
      shadow: "shadow.md",
    },
  } as DesignProps,
  // ===== ОСНОВНЫЕ ДЕЙСТВИЯ =====
  primary: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    bg: "color.primary",
    color: "color.text.inverse",
    padding: 2,
    radius: "radius.sm",
    border: "none",
    fontWeight: "typography.fontWeight.semibold",
    fontSize: "typography.fontSize.md",
    cursor: "pointer",
    transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    shadow: "shadow.md",
    hover: {
      transform: "translateY(-2px)",
      shadow: "shadow.lg",
    },
    active: {
      transform: "translateY(0)",
      shadow: "shadow.sm",
    },
  } as DesignProps,

  secondary: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    bg: "color.secondary",
    color: "color.text.inverse",
    padding: 2,
    radius: "radius.sm",
    border: "none",
    fontWeight: "typography.fontWeight.semibold",
    fontSize: "typography.fontSize.md",
    cursor: "pointer",
    transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    shadow: "shadow.md",
    hover: {
      transform: "translateY(-2px)",
      shadow: "shadow.lg",
    },
    active: {
      transform: "translateY(0)",
      shadow: "shadow.sm",
    },
  } as DesignProps,

  success: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    bg: "color.success",
    color: "color.text.inverse",
    padding: 2,
    radius: "radius.sm",
    border: "none",
    fontWeight: "typography.fontWeight.semibold",
    fontSize: "typography.fontSize.md",
    cursor: "pointer",
    transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    shadow: "shadow.md",
    hover: {
      transform: "translateY(-2px)",
      shadow: "shadow.lg",
    },
    active: {
      transform: "translateY(0)",
      shadow: "shadow.sm",
    },
  } as DesignProps,

  warning: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    bg: "color.warning",
    color: "color.text.inverse",
    padding: 2,
    radius: "radius.sm",
    border: "none",
    fontWeight: "typography.fontWeight.semibold",
    fontSize: "typography.fontSize.md",
    cursor: "pointer",
    transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    shadow: "shadow.md",
    hover: {
      transform: "translateY(-2px)",
      shadow: "shadow.lg",
    },
    active: {
      transform: "translateY(0)",
      shadow: "shadow.sm",
    },
  } as DesignProps,

  danger: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    bg: "color.danger",
    color: "color.text.inverse",
    padding: 2,
    radius: "radius.sm",
    border: "none",
    fontWeight: "typography.fontWeight.semibold",
    fontSize: "typography.fontSize.md",
    cursor: "pointer",
    transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    shadow: "shadow.md",
    hover: {
      transform: "translateY(-2px)",
      shadow: "shadow.lg",
    },
    active: {
      transform: "translateY(0)",
      shadow: "shadow.sm",
    },
  } as DesignProps,

  info: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    bg: "color.primary",
    color: "color.text.inverse",
    padding: 2,
    radius: "radius.sm",
    border: "none",
    fontWeight: "typography.fontWeight.semibold",
    fontSize: "typography.fontSize.md",
    cursor: "pointer",
    transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    shadow: "shadow.md",
    hover: {
      transform: "translateY(-2px)",
      shadow: "shadow.lg",
    },
    active: {
      transform: "translateY(0)",
      shadow: "shadow.sm",
    },
  } as DesignProps,

  // ===== КОНТУРНЫЕ =====
  outline: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    bg: "transparent",
    color: "color.primary",
    padding: 2,
    radius: "radius.sm",
    border: "2px solid",
    borderColor: "color.primary",
    fontWeight: "typography.fontWeight.semibold",
    fontSize: "typography.fontSize.md",
    cursor: "pointer",
    transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    shadow: "shadow.md",
    hover: {
      bg: "color.primary",
      color: "color.text.inverse",
      transform: "translateY(-2px)",
      shadow: "shadow.lg",
    },
    active: {
      transform: "translateY(0)",
      shadow: "shadow.sm",
    },
    selected: {
      bg: "color.primary",
      color: "color.text.inverse",
      shadow: "shadow.lg",
    },
  } as DesignProps,

  outlineSuccess: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    bg: "transparent",
    color: "color.success",
    padding: 2,
    radius: "radius.sm",
    border: "2px solid",
    borderColor: "color.success",
    fontWeight: "typography.fontWeight.semibold",
    fontSize: "typography.fontSize.md",
    cursor: "pointer",
    transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    shadow: "shadow.md",
    hover: {
      bg: "color.success",
      color: "color.text.inverse",
      transform: "translateY(-2px)",
      shadow: "shadow.lg",
    },
    active: {
      transform: "translateY(0)",
      shadow: "shadow.sm",
    },
    selected: {
      bg: "color.success",
      color: "color.text.inverse",
      shadow: "shadow.lg",
    },
  } as DesignProps,

  outlineDanger: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    bg: "transparent",
    color: "color.danger",
    padding: 2,
    radius: "radius.sm",
    border: "2px solid",
    borderColor: "color.danger",
    fontWeight: "typography.fontWeight.semibold",
    fontSize: "typography.fontSize.md",
    cursor: "pointer",
    transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    shadow: "shadow.md",
    hover: {
      bg: "color.danger",
      color: "color.text.inverse",
      transform: "translateY(-2px)",
      shadow: "shadow.lg",
    },
    active: {
      transform: "translateY(0)",
      shadow: "shadow.sm",
    },
    selected: {
      bg: "color.danger",
      color: "color.text.inverse",
      shadow: "shadow.lg",
    },
  } as DesignProps,

  outlineWarning: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    bg: "transparent",
    color: "color.warning",
    padding: 2,
    radius: "radius.sm",
    border: "2px solid",
    borderColor: "color.warning",
    fontWeight: "typography.fontWeight.semibold",
    fontSize: "typography.fontSize.md",
    cursor: "pointer",
    transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    shadow: "shadow.md",
    hover: {
      bg: "color.warning",
      color: "color.text.inverse",
      transform: "translateY(-2px)",
      shadow: "shadow.lg",
    },
    active: {
      transform: "translateY(0)",
      shadow: "shadow.sm",
    },
    selected: {
      bg: "color.warning",
      color: "color.text.inverse",
      shadow: "shadow.lg",
    },
  } as DesignProps,

  outlineInfo: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    bg: "transparent",
    color: "color.primary",
    padding: 2,
    radius: "radius.sm",
    border: "2px solid",
    borderColor: "color.primary",
    fontWeight: "typography.fontWeight.semibold",
    fontSize: "typography.fontSize.md",
    cursor: "pointer",
    transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    shadow: "shadow.md",
    hover: {
      bg: "color.primary",
      color: "color.text.inverse",
      transform: "translateY(-2px)",
      shadow: "shadow.lg",
    },
    active: {
      transform: "translateY(0)",
      shadow: "shadow.sm",
    },
    selected: {
      bg: "color.primary",
      color: "color.text.inverse",
      shadow: "shadow.lg",
    },
  } as DesignProps,

  // ===== МЯГКИЕ =====
  soft: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    bg: "color.bg.primary",
    color: "color.text.primary",
    padding: 2,
    radius: "radius.sm",
    border: "none",
    fontWeight: "typography.fontWeight.semibold",
    fontSize: "typography.fontSize.md",
    cursor: "pointer",
    transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    shadow: "shadow.md",
    hover: {
      bg: "color.bg.secondary",
      transform: "translateY(-2px)",
      shadow: "shadow.lg",
    },
    active: {
      transform: "translateY(0)",
      shadow: "shadow.sm",
    },
    selected: {
      bg: "color.bg.secondary",
      shadow: "shadow.sm",
    },
  } as DesignProps,

  softPrimary: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    bg: "color.bg.tertiary",
    color: "color.primary",
    padding: 2,
    radius: "radius.sm",
    border: "none",
    fontWeight: "typography.fontWeight.semibold",
    fontSize: "typography.fontSize.md",
    cursor: "pointer",
    transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    shadow: "shadow.md",
    hover: {
      bg: "color.bg.tertiary",
      transform: "translateY(-2px)",
      shadow: "shadow.lg",
    },
    active: {
      transform: "translateY(0)",
      shadow: "shadow.sm",
    },
    selected: {
      bg: "color.primary",
      color: "color.text.inverse",
      shadow: "shadow.lg",
    },
  } as DesignProps,

  softSuccess: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    bg: "color.bg.tertiary",
    color: "color.success",
    padding: 2,
    radius: "radius.sm",
    border: "none",
    fontWeight: "typography.fontWeight.semibold",
    fontSize: "typography.fontSize.md",
    cursor: "pointer",
    transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    shadow: "shadow.md",
    hover: {
      bg: "color.bg.tertiary",
      transform: "translateY(-2px)",
      shadow: "shadow.lg",
    },
    active: {
      transform: "translateY(0)",
      shadow: "shadow.sm",
    },
    selected: {
      bg: "color.success",
      color: "color.text.inverse",
      shadow: "shadow.lg",
    },
  } as DesignProps,

  softDanger: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    bg: "color.bg.tertiary",
    color: "color.danger",
    padding: 2,
    radius: "radius.sm",
    border: "none",
    fontWeight: "typography.fontWeight.semibold",
    fontSize: "typography.fontSize.md",
    cursor: "pointer",
    transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    shadow: "shadow.md",
    hover: {
      bg: "color.bg.tertiary",
      transform: "translateY(-2px)",
      shadow: "shadow.lg",
    },
    active: {
      transform: "translateY(0)",
      shadow: "shadow.sm",
    },
    selected: {
      bg: "color.danger",
      color: "color.text.inverse",
      shadow: "shadow.lg",
    },
  } as DesignProps,

  softWarning: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    bg: "color.bg.tertiary",
    color: "color.warning",
    padding: 2,
    radius: "radius.sm",
    border: "none",
    fontWeight: "typography.fontWeight.semibold",
    fontSize: "typography.fontSize.md",
    cursor: "pointer",
    transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    shadow: "shadow.md",
    hover: {
      bg: "color.bg.tertiary",
      transform: "translateY(-2px)",
      shadow: "shadow.lg",
    },
    active: {
      transform: "translateY(0)",
      shadow: "shadow.sm",
    },
    selected: {
      bg: "color.warning",
      color: "color.text.inverse",
      shadow: "shadow.lg",
    },
  } as DesignProps,

  softInfo: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    bg: "color.bg.tertiary",
    color: "color.primary",
    padding: 2,
    radius: "radius.sm",
    border: "none",
    fontWeight: "typography.fontWeight.semibold",
    fontSize: "typography.fontSize.md",
    cursor: "pointer",
    transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    shadow: "shadow.md",
    hover: {
      bg: "color.bg.tertiary",
      transform: "translateY(-2px)",
      shadow: "shadow.lg",
    },
    active: {
      transform: "translateY(0)",
      shadow: "shadow.sm",
    },
    selected: {
      bg: "color.primary",
      color: "color.text.inverse",
      shadow: "shadow.lg",
    },
  } as DesignProps,

  // ===== ПРИЗРАК =====
  ghost: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    bg: "transparent",
    color: "color.text.primary",
    padding: 2,
    radius: "radius.sm",
    border: "none",
    fontWeight: "typography.fontWeight.semibold",
    fontSize: "typography.fontSize.md",
    cursor: "pointer",
    transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    hover: {
      bg: "rgb(255 255 255 / 20%)",
      transform: "translateY(-1px)",
      shadow: "shadow.lg",
    },
    active: {
      transform: "translateY(0)",
      shadow: "shadow.sm",
    },
    selected: {
      bg: "color.bg.secondary",
      shadow: "shadow.sm",
    },
  } as DesignProps,

  // ===== СТЕКЛЯННЫЕ =====
  glass: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    bg: "rgba(255, 255, 255, 0.1)",
    backdropFilter: "blur(20px)",
    color: "color.text.inverse",
    padding: 2,
    radius: "radius.lg",
    border: "1px solid",
    borderColor: "rgba(255, 255, 255, 0.2)",
    fontWeight: "typography.fontWeight.semibold",
    fontSize: "typography.fontSize.md",
    cursor: "pointer",
    transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    shadow: "shadow.lg",
    hover: {
      bg: "rgba(255, 255, 255, 0.15)",
      borderColor: "rgba(255, 255, 255, 0.3)",
      transform: "translateY(-2px)",
      shadow: "shadow.lg",
    },
    active: {
      transform: "translateY(0)",
      shadow: "shadow.sm",
    },
  } as DesignProps,

  glassDark: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    bg: "rgba(0, 0, 0, 0.3)",
    backdropFilter: "blur(20px)",
    color: "color.text.inverse",
    padding: 2,
    radius: "radius.lg",
    border: "1px solid",
    borderColor: "rgba(255, 255, 255, 0.1)",
    fontWeight: "typography.fontWeight.semibold",
    fontSize: "typography.fontSize.md",
    cursor: "pointer",
    transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    shadow: "shadow.lg",
    hover: {
      bg: "rgba(0, 0, 0, 0.4)",
      transform: "translateY(-2px)",
      shadow: "shadow.lg",
    },
    active: {
      transform: "translateY(0)",
      shadow: "shadow.sm",
    },
  } as DesignProps,

  // ===== СПЕЦИАЛЬНЫЕ =====
  pill: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    bg: "color.primary",
    color: "color.text.inverse",
    padding: "10px 20px",
    radius: "radius.full",
    border: "none",
    fontWeight: "typography.fontWeight.semibold",
    fontSize: "typography.fontSize.sm",
    cursor: "pointer",
    transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    shadow: "shadow.md",
    hover: {
      transform: "scale(1.05)",
      shadow: "shadow.lg",
    },
    active: {
      transform: "translateY(0)",
      shadow: "shadow.sm",
    },
  } as DesignProps,

  hero: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
    bg: "color.primary",
    color: "color.text.inverse",
    padding: "18px 36px",
    radius: "radius.lg",
    border: "none",
    fontWeight: "typography.fontWeight.bold",
    fontSize: "typography.fontSize.lg",
    cursor: "pointer",
    transition: "all 0.4s cubic-bezier(0.4, 0, 0.2, 1)",
    shadow: "shadow.lg",
    hover: {
      transform: "translateY(-3px) scale(1.02)",
      shadow: "shadow.lg",
    },
    active: {
      transform: "translateY(0)",
      shadow: "shadow.sm",
    },
  } as DesignProps,

  cta: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    bg: "color.danger",
    color: "color.text.inverse",
    padding: "14px 28px",
    radius: "radius.md",
    border: "none",
    fontWeight: "typography.fontWeight.bold",
    fontSize: "typography.fontSize.lg",
    cursor: "pointer",
    transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    shadow: "shadow.lg",
    hover: {
      transform: "translateY(-2px)",
      shadow: "shadow.lg",
    },
    active: {
      transform: "translateY(0)",
      shadow: "shadow.sm",
    },
  } as DesignProps,

  // ===== КРЕАТИВНЫЕ =====
  // Эти presets остаются с жестко заданными значениями, так как они специфичны для определенного стиля
  neon: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    bg: "#000000",
    color: "#00ffff",
    padding: 2,
    radius: "radius.sm",
    border: "2px solid #00ffff",
    fontWeight: "typography.fontWeight.bold",
    fontSize: "typography.fontSize.md",
    cursor: "pointer",
    transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    shadow: "0 0 20px #00ffff, inset 0 0 10px rgba(0, 255, 255, 0.3)",
    hover: {
      bg: "#00ffff",
      color: "#000000",
      shadow: "0 0 30px #00ffff, inset 0 0 15px rgba(0, 255, 255, 0.5)",
      transform: "translateY(-2px)",
    },
    active: {
      transform: "translateY(0)",
    },
  } as DesignProps,

  cyberpunk: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    bg: "#0d0221",
    color: "#00eaff",
    padding: 2,
    radius: "radius.sm",
    border: "2px solid #ff0099",
    fontWeight: "typography.fontWeight.bold",
    fontSize: "typography.fontSize.md",
    cursor: "pointer",
    transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    shadow: "0 0 20px rgba(255, 0, 153, 0.6), inset 0 0 10px rgba(0, 234, 255, 0.3)",
    hover: {
      bg: "#ff0099",
      color: "#ffffff",
      shadow: "0 0 30px rgba(255, 0, 153, 0.8), inset 0 0 15px rgba(255, 0, 153, 0.5)",
      transform: "translateY(-2px)",
    },
    active: {
      transform: "translateY(0)",
    },
  } as DesignProps,

  gradient: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    bg: "linear-gradient(135deg, #f093fb 0%, #f5576c 100%)",
    color: "color.text.inverse",
    padding: 2,
    radius: "radius.md",
    border: "none",
    fontWeight: "typography.fontWeight.semibold",
    fontSize: "typography.fontSize.md",
    cursor: "pointer",
    transition: "all 0.4s cubic-bezier(0.4, 0, 0.2, 1)",
    shadow: "shadow.lg",
    hover: {
      bg: "linear-gradient(135deg, #f5576c 0%, #f093fb 100%)",
      transform: "translateY(-2px) scale(1.02)",
      shadow: "shadow.lg",
    },
    active: {
      transform: "translateY(0) scale(1)",
    },
  } as DesignProps,

  // ===== НАВИГАЦИЯ =====
  nav: {
    display: "flex",
    alignItems: "center",
    width: "100%",
    justifyContent: "flex-start",
    padding: 2,
    gap: 3,
    position: "relative",
    transition: "all 0.2s cubic-bezier(0.4, 0, 0.2, 1)",
    borderRadius: "radius.md",
    bg: "transparent",
    color: "color.text.secondary",
    fontWeight: "typography.fontWeight.medium",
    fontSize: "typography.fontSize.sm",
    minHeight: "44px",
    border: "none",
    cursor: "pointer",
    hover: {
      bg: "color.bg.tertiary",
    },
  } as DesignProps,

  navActive: {
    display: "flex",
    alignItems: "center",
    width: "100%",
    justifyContent: "flex-start",
    padding: 2,
    gap: 3,
    position: "relative",
    transition: "all 0.2s cubic-bezier(0.4, 0, 0.2, 1)",
    borderRadius: "radius.md",
    bg: "color.primary",
    color: "color.text.inverse",
    fontWeight: "typography.fontWeight.semibold",
    fontSize: "typography.fontSize.sm",
    minHeight: "44px",
    border: "none",
    cursor: "pointer",
    hover: {
      bg: "color.primary",
      opacity: 0.9,
    },
  } as DesignProps,

  // ===== INPUT =====
  input: {
    padding: 2,
    radius: "radius.md",
    border: "2px solid",
    borderColor: "color.bg.tertiary",
    bg: "color.bg.primary",
    color: "color.text.primary",
    fontSize: "typography.fontSize.md",
    fontWeight: "typography.fontWeight.medium",
    transition: "all 0.2s cubic-bezier(0.4, 0, 0.2, 1)",
    outline: "none",
    focus: {
      borderColor: "color.primary",
      shadow: "shadow.sm",
    },
  } as DesignProps,

  inputSoft: {
    padding: 2,
    radius: "radius.md",
    border: "none",
    bg: "color.bg.tertiary",
    color: "color.text.primary",
    fontSize: "typography.fontSize.md",
    fontWeight: "typography.fontWeight.medium",
    transition: "all 0.2s cubic-bezier(0.4, 0, 0.2, 1)",
    outline: "none",
    focus: {
      bg: "color.bg.tertiary",
      shadow: "shadow.sm",
    },
  } as DesignProps,

  inputOutline: {
    padding: 2,
    radius: "radius.md",
    border: "2px solid",
    borderColor: "color.primary",
    bg: "transparent",
    color: "color.text.primary",
    fontSize: "typography.fontSize.md",
    fontWeight: "typography.fontWeight.medium",
    transition: "all 0.2s cubic-bezier(0.4, 0, 0.2, 1)",
    outline: "none",
    focus: {
      borderColor: "color.primary",
      shadow: "shadow.sm",
    },
  } as DesignProps,

  // ===== МОДАЛЬНЫЕ ОКНА =====
  modal: {
    bg: "color.bg.primary",
    radius: "radius.lg",
    shadow: "shadow.lg",
    border: "none",
    overflow: "hidden",
    position: "relative",
  } as DesignProps,

  // ===== БЕЙДЖИ =====
  badge: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "4px 8px",
    radius: "radius.full",
    bg: "color.bg.tertiary",
    color: "color.text.primary",
    fontSize: "typography.fontSize.xs",
    fontWeight: "typography.fontWeight.medium",
    shadow: "shadow.sm",
    transition: "all 0.2s ease",
    hover: {
      filter: "saturate(0.5)",
      shadow: "shadow.md",
      transform: "translateY(-1px)",
    },
    active: {
      transform: "translateY(0)",
      shadow: "shadow.sm",
    },
  } as DesignProps,

  badgePrimary: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "4px 8px",
    radius: "radius.full",
    bg: "color.primary",
    color: "color.text.inverse",
    fontSize: "typography.fontSize.xs",
    fontWeight: "typography.fontWeight.medium",
    shadow: "shadow.sm",
    transition: "all 0.2s ease",
    hover: {
      filter: "saturate(0.5)",
      shadow: "shadow.md",
      transform: "translateY(-1px)",
    },
    active: {
      transform: "translateY(0)",
      shadow: "shadow.sm",
    },
  } as DesignProps,

  badgeSuccess: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "4px 8px",
    radius: "radius.full",
    bg: "color.success",
    color: "color.text.inverse",
    fontSize: "typography.fontSize.xs",
    fontWeight: "typography.fontWeight.medium",
    shadow: "shadow.sm",
    transition: "all 0.2s ease",
    hover: {
      filter: "saturate(0.5)",
      shadow: "shadow.md",
      transform: "translateY(-1px)",
    },
    active: {
      transform: "translateY(0)",
      shadow: "shadow.sm",
    },
  } as DesignProps,

  badgeWarning: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "4px 8px",
    radius: "radius.full",
    bg: "color.warning",
    color: "color.text.inverse",
    fontSize: "typography.fontSize.xs",
    fontWeight: "typography.fontWeight.medium",
    shadow: "shadow.sm",
    transition: "all 0.2s ease",
    hover: {
      filter: "saturate(0.5)",
      shadow: "shadow.md",
      transform: "translateY(-1px)",
    },
    active: {
      transform: "translateY(0)",
      shadow: "shadow.sm",
    },
  } as DesignProps,

  badgeDanger: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "4px 8px",
    radius: "radius.full",
    bg: "color.danger",
    color: "color.text.inverse",
    fontSize: "typography.fontSize.xs",
    fontWeight: "typography.fontWeight.medium",
    shadow: "shadow.sm",
    transition: "all 0.2s ease",
    hover: {
      filter: "saturate(0.5)",
      shadow: "shadow.md",
      transform: "translateY(-1px)",
    },
    active: {
      transform: "translateY(0)",
      shadow: "shadow.sm",
    },
  } as DesignProps,

  badgeSecondary: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "4px 8px",
    radius: "radius.full",
    bg: "color.secondary",
    color: "color.text.inverse",
    fontSize: "typography.fontSize.xs",
    fontWeight: "typography.fontWeight.medium",
    shadow: "shadow.sm",
    transition: "all 0.2s ease",
    hover: {
      filter: "saturate(0.5)",
      shadow: "shadow.md",
      transform: "translateY(-1px)",
    },
    active: {
      transform: "translateY(0)",
      shadow: "shadow.sm",
    },
  } as DesignProps,

  badgeInfo: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "4px 8px",
    radius: "radius.full",
    bg: "color.primary",
    color: "color.text.inverse",
    fontSize: "typography.fontSize.xs",
    fontWeight: "typography.fontWeight.medium",
    shadow: "shadow.sm",
    transition: "all 0.2s ease",
    hover: {
      filter: "saturate(0.5)",
      shadow: "shadow.md",
      transform: "translateY(-1px)",
    },
    active: {
      transform: "translateY(0)",
      shadow: "shadow.sm",
    },
  } as DesignProps,

  badgeSoft: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "4px 8px",
    radius: "radius.full",
    bg: "color.bg.tertiary",
    color: "color.text.secondary",
    fontSize: "typography.fontSize.xs",
    fontWeight: "typography.fontWeight.medium",
    shadow: "shadow.sm",
    transition: "all 0.2s ease",
    hover: {
      filter: "saturate(0.5)",
      shadow: "shadow.md",
      transform: "translateY(-1px)",
    },
    active: {
      transform: "translateY(0)",
      shadow: "shadow.sm",
    },
  } as DesignProps,

  badgeOutline: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "4px 8px",
    radius: "radius.full",
    bg: "transparent",
    color: "color.primary",
    border: "1px solid",
    borderColor: "color.primary",
    fontSize: "typography.fontSize.xs",
    fontWeight: "typography.fontWeight.medium",
    transition: "all 0.2s ease",
    hover: {
      filter: "saturate(0.5)",
      color: "color.text.inverse",
      shadow: "shadow.sm",
      transform: "translateY(-1px)",
    },
    active: {
      transform: "translateY(0)",
      shadow: "shadow.sm",
    },
  } as DesignProps,
} as const;

export type PresetName = keyof typeof presets;
