// Internal handlers for Kanban board (generated by CLI make event)
export const kanbanHandlers = `package main

import (
  "context"
  "encoding/json"
  "time"

  "github.com/google/uuid"
  "github.com/gorilla/websocket"
  "vira-engine-backend/internal/events"
)

// handleKanbanCardCreate handles kanban.card.create events.
func handleKanbanCardCreate(ctx context.Context, hub events.EventEmitter, conn *websocket.Conn, msg events.WSMessage) {
  var payload struct {
    BoardID     string \`json:"boardId"\`
    ColumnID    string \`json:"columnId"\`
    Title       string \`json:"title"\`
    Description string \`json:"description,omitempty"\`
    At          int64  \`json:"at"\`
  }
  if err := json.Unmarshal(msg.Data, &payload); err != nil {
    return
  }

  channel := events.ChannelKanban(payload.BoardID)
  snap, version, ok := hub.Snapshot(channel)
  if !ok {
    // Initialize board
    initialBoard := map[string]any{
      "id":        payload.BoardID,
      "title":     "Kanban Board",
      "columns":   []any{},
      "cards":     map[string]any{},
      "createdAt": time.Now().UnixMilli(),
      "updatedAt": time.Now().UnixMilli(),
    }
    hub.Update(channel, initialBoard)
    snap, _, _ = hub.Snapshot(channel)
  }

  var board map[string]any
  if err := json.Unmarshal(snap, &board); err != nil {
    return
  }

  // Create new card
  cardID := uuid.NewString()
  newCard := map[string]any{
    "id":         cardID,
    "title":      payload.Title,
    "description": payload.Description,
    "columnId":   payload.ColumnID,
    "order":      0,
    "createdAt":  payload.At,
    "updatedAt":  payload.At,
  }

  cards, _ := board["cards"].(map[string]any)
  if cards == nil {
    cards = make(map[string]any)
  }
  cards[cardID] = newCard
  board["cards"] = cards

  // Add to column
  columns, _ := board["columns"].([]any)
  for i, colRaw := range columns {
    col, _ := colRaw.(map[string]any)
    if col["id"] == payload.ColumnID {
      cardIds, _ := col["cardIds"].([]any)
      if cardIds == nil {
        cardIds = []any{}
      }
      col["cardIds"] = append(cardIds, cardID)
      columns[i] = col
      break
    }
  }
  board["columns"] = columns
  board["updatedAt"] = time.Now().UnixMilli()

  hub.Update(channel, board)
}

// handleKanbanCardMove handles kanban.card.move events.
func handleKanbanCardMove(ctx context.Context, hub events.EventEmitter, conn *websocket.Conn, msg events.WSMessage) {
  var payload struct {
    BoardID     string \`json:"boardId"\`
    CardID      string \`json:"cardId"\`
    FromColumnID string \`json:"fromColumnId"\`
    ToColumnID  string \`json:"toColumnId"\`
    NewOrder    int    \`json:"newOrder"\`
    At          int64  \`json:"at"\`
  }
  if err := json.Unmarshal(msg.Data, &payload); err != nil {
    return
  }

  channel := events.ChannelKanban(payload.BoardID)
  snap, _, ok := hub.Snapshot(channel)
  if !ok {
    return
  }

  var board map[string]any
  if err := json.Unmarshal(snap, &board); err != nil {
    return
  }

  // Update card columnId
  cards, _ := board["cards"].(map[string]any)
  if card, ok := cards[payload.CardID].(map[string]any); ok {
    card["columnId"] = payload.ToColumnID
    card["order"] = payload.NewOrder
    card["updatedAt"] = payload.At
    cards[payload.CardID] = card
  }

  // Remove from old column
  columns, _ := board["columns"].([]any)
  for i, colRaw := range columns {
    col, _ := colRaw.(map[string]any)
    if col["id"] == payload.FromColumnID {
      cardIds, _ := col["cardIds"].([]any)
      newCardIds := []any{}
      for _, id := range cardIds {
        if idStr, _ := id.(string); idStr != payload.CardID {
          newCardIds = append(newCardIds, id)
        }
      }
      col["cardIds"] = newCardIds
      columns[i] = col
    }
    // Add to new column
    if col["id"] == payload.ToColumnID {
      cardIds, _ := col["cardIds"].([]any)
      if cardIds == nil {
        cardIds = []any{}
      }
      // Insert at position
      newCardIds := make([]any, len(cardIds)+1)
      copy(newCardIds, cardIds[:payload.NewOrder])
      newCardIds[payload.NewOrder] = payload.CardID
      copy(newCardIds[payload.NewOrder+1:], cardIds[payload.NewOrder:])
      col["cardIds"] = newCardIds
      columns[i] = col
    }
  }
  board["columns"] = columns
  board["updatedAt"] = time.Now().UnixMilli()

  hub.Update(channel, board)
}

// handleKanbanCardDelete handles kanban.card.delete events.
func handleKanbanCardDelete(ctx context.Context, hub events.EventEmitter, conn *websocket.Conn, msg events.WSMessage) {
  var payload struct {
    BoardID string \`json:"boardId"\`
    CardID  string \`json:"cardId"\`
    At      int64  \`json:"at"\`
  }
  if err := json.Unmarshal(msg.Data, &payload); err != nil {
    return
  }

  channel := events.ChannelKanban(payload.BoardID)
  snap, _, ok := hub.Snapshot(channel)
  if !ok {
    return
  }

  var board map[string]any
  if err := json.Unmarshal(snap, &board); err != nil {
    return
  }

  // Remove card
  cards, _ := board["cards"].(map[string]any)
  var cardColumnID string
  if card, ok := cards[payload.CardID].(map[string]any); ok {
    cardColumnID, _ = card["columnId"].(string)
    delete(cards, payload.CardID)
  }
  board["cards"] = cards

  // Remove from column
  if cardColumnID != "" {
    columns, _ := board["columns"].([]any)
    for i, colRaw := range columns {
      col, _ := colRaw.(map[string]any)
      if col["id"] == cardColumnID {
        cardIds, _ := col["cardIds"].([]any)
        newCardIds := []any{}
        for _, id := range cardIds {
          if idStr, _ := id.(string); idStr != payload.CardID {
            newCardIds = append(newCardIds, id)
          }
        }
        col["cardIds"] = newCardIds
        columns[i] = col
        break
      }
    }
    board["columns"] = columns
  }
  board["updatedAt"] = time.Now().UnixMilli()

  hub.Update(channel, board)
}

func init() {
  events.Register("kanban.card.create", handleKanbanCardCreate)
  events.Register("kanban.card.move", handleKanbanCardMove)
  events.Register("kanban.card.delete", handleKanbanCardDelete)
}
`;

