export const registryGo = `package events

// Registry holds all registered event handlers.
var Registry = make(map[string]EventHandler)

// Register registers an event handler by name.
func Register(name string, handler EventHandler) {
  Registry[name] = handler
}

// RegisterAll registers multiple handlers at once.
func RegisterAll(handlers map[string]EventHandler) {
  for name, handler := range handlers {
    Registry[name] = handler
  }
}

// Get returns a handler by name.
func Get(name string) (EventHandler, bool) {
  handler, ok := Registry[name]
  return handler, ok
}

// Apply registers all handlers from Registry into a Hub.
func (h *Hub) ApplyRegistry() {
  h.mu.Lock()
  defer h.mu.Unlock()
  for name, handler := range Registry {
    h.events[name] = handler
  }
}

// Example handler registration (auto-generated by CLI):
// func init() {
//   Register("demo.echo", handleDemoEvent)
//   Register("task.update", handleTaskUpdate)
//   Register("user.setStatus", handleUserStatus)
// }
`;

